In [1]:
import numpy as np
import pandas as pd

In [2]:
l = ["sudh", 1,2,3,4]

In [3]:
type(l)

list

In [4]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [5]:
type(np.array(l))

numpy.ndarray

In [6]:
a1 = np.array([3,2,4,5,6,3.0])

In [7]:
a = np.array([[1,2],[3,4]])

In [8]:
a

array([[1, 2],
       [3, 4]])

In [9]:
a[1][1]

4

In [10]:
a1

array([3., 2., 4., 5., 6., 3.])

In [11]:
a1[2]

4.0

In [12]:
a2 = np.array([1,2,3,4],ndmin=4)

In [13]:
a2

array([[[[1, 2, 3, 4]]]])

In [14]:
a2[0][0][0][0]

1

In [15]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [16]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [17]:
np.mat([1,2,3,4,5]) # minimun 2 dimension

matrix([[1, 2, 3, 4, 5]])

In [18]:
a = [1,2,3,4,5]

In [19]:
np.asarray(a)

array([1, 2, 3, 4, 5])

In [20]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [21]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [22]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [23]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
np.fromfunction(lambda i, j : i*j, (4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [25]:
np.mat(np.fromfunction(lambda i, j : i*j, (4,4), dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [26]:
np.fromfunction(lambda i, j,z : i*j*z, (4,3,2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [27]:
a = np.fromfunction(lambda i, j,z,p : i*j*z*p, (4,3,2,2), dtype=int)

In [28]:
Job Location- Work From Home
Interested candidates can share their resumes at Whatsapp Divya Ma'am: +918928482266

For more details Please Contact on +918928482266

SyntaxError: invalid syntax (Temp/ipykernel_9624/1995618633.py, line 1)

In [29]:
a

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [30]:
a = np.fromfunction(lambda i, j,z: i*j*z, (4,3,2), dtype=int)

In [31]:
a.shape

(4, 3, 2)

In [32]:
a.ndim

3

In [33]:
a.size

24

In [34]:
a.dtype

dtype('int32')

In [35]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [36]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [ ]:
a = np.fromfunction(lambda i, j: i*j, (100,100), dtype=int)

In [37]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [38]:
np.random.rand(100,4)

array([[0.30365064, 0.02939872, 0.84634853, 0.54763461],
       [0.82953341, 0.7867899 , 0.16369048, 0.49000345],
       [0.05295068, 0.43202194, 0.43612172, 0.85060342],
       [0.58005969, 0.44327759, 0.41943103, 0.93183541],
       [0.46560568, 0.69886746, 0.60465968, 0.18386878],
       [0.22738091, 0.89723624, 0.3184002 , 0.57678087],
       [0.83225232, 0.97609919, 0.18168895, 0.6494802 ],
       [0.5175432 , 0.78427414, 0.06806575, 0.71789854],
       [0.65870975, 0.72397577, 0.62474041, 0.32750589],
       [0.9426908 , 0.6654914 , 0.40237425, 0.64597238],
       [0.42820643, 0.16161587, 0.12295448, 0.69384083],
       [0.91670554, 0.8926589 , 0.35516533, 0.13113624],
       [0.3076265 , 0.29028956, 0.97462054, 0.14349464],
       [0.84199637, 0.24809503, 0.81711023, 0.47445673],
       [0.96238597, 0.59314181, 0.87173721, 0.09316753],
       [0.35353025, 0.50166533, 0.21085025, 0.95882826],
       [0.38019106, 0.64302204, 0.37475718, 0.78903853],
       [0.10344429, 0.75633427,

In [39]:
np.random.randint(4,50)

48

In [40]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  0.738506 -0.198559  1.595456 -0.026090  0.516947
1 -0.264953 -0.797369  0.341426  0.088234 -1.183219
2  0.672125 -0.603864  0.036910  0.625731 -1.885932
3  0.004868 -0.376740 -0.650410  0.031064  0.561671

In [41]:
a = np.fromfunction(lambda i, j,z: i*j*z, (4,3,2), dtype=int)
a.size

24

In [42]:
a.reshape(4,2,1,3,1,1)

array([[[[[[0]],

          [[0]],

          [[0]]]],



        [[[[0]],

          [[0]],

          [[0]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[1]],

          [[0]],

          [[2]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[2]],

          [[0]],

          [[4]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[3]],

          [[0]],

          [[6]]]]]])

In [43]:
a.reshape(4,3,2)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [44]:
 a.reshape(4,-1) # here -1 is the remaing fraction of a took by function

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [45]:
a.reshape(2,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [46]:
a.reshape(2,-12345) # any negative number will work 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [47]:
a.reshape(2,4,-125)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [48]:
pd.DataFrame(a.reshape(6,4)) # must be the fraction of size of a

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [49]:
list(range(4,10,2))

[4, 6, 8]

In [50]:
a1 = list(np.arange(4,10.5,0.2))

In [51]:
a1

[4.0,
 4.2,
 4.4,
 4.6000000000000005,
 4.800000000000001,
 5.000000000000001,
 5.200000000000001,
 5.400000000000001,
 5.600000000000001,
 5.800000000000002,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.800000000000003,
 8.000000000000004,
 8.200000000000003,
 8.400000000000004,
 8.600000000000005,
 8.800000000000004,
 9.000000000000004,
 9.200000000000005,
 9.400000000000006,
 9.600000000000005,
 9.800000000000004,
 10.000000000000005,
 10.200000000000006,
 10.400000000000006]

In [52]:
a1[1:4]

[4.2, 4.4, 4.6000000000000005]

In [53]:
arr = np.random.rand(4,5)

In [54]:
arr

array([[0.5134059 , 0.34193052, 0.27742946, 0.34954346, 0.37795785],
       [0.52183453, 0.87843501, 0.54093144, 0.42051613, 0.82038419],
       [0.37098616, 0.78956852, 0.46999119, 0.18222166, 0.71513626],
       [0.3908785 , 0.373599  , 0.49358602, 0.54740971, 0.07362113]])

In [55]:
arr[arr > 0.5]

array([0.5134059 , 0.52183453, 0.87843501, 0.54093144, 0.82038419,
       0.78956852, 0.71513626, 0.54740971])

In [56]:
arr[1:3,2:3]

array([[0.54093144],
       [0.46999119]])

In [57]:
arr[[1,2],[2]]

array([0.54093144, 0.46999119])

In [58]:
arr = np.random.rand(8,5)

In [59]:
arr

array([[0.91100284, 0.87254985, 0.87599047, 0.52100726, 0.18977714],
       [0.96534491, 0.17805549, 0.57196417, 0.2220053 , 0.54179187],
       [0.34764924, 0.40647143, 0.29199625, 0.40811595, 0.6524757 ],
       [0.40677557, 0.24975673, 0.96702641, 0.82891978, 0.38249632],
       [0.90040327, 0.61196352, 0.85995196, 0.38679557, 0.00195376],
       [0.20660382, 0.84639322, 0.45869684, 0.57043259, 0.14048069],
       [0.43180773, 0.77621717, 0.17960785, 0.12568439, 0.14316812],
       [0.57433589, 0.02781011, 0.80034891, 0.12366433, 0.37597842]])

In [60]:
arr[1:8,0:2]

array([[0.96534491, 0.17805549],
       [0.34764924, 0.40647143],
       [0.40677557, 0.24975673],
       [0.90040327, 0.61196352],
       [0.20660382, 0.84639322],
       [0.43180773, 0.77621717],
       [0.57433589, 0.02781011]])

In [61]:
a2 = arr[1:8,[0,1,2]]

In [62]:
a2

array([[0.96534491, 0.17805549, 0.57196417],
       [0.34764924, 0.40647143, 0.29199625],
       [0.40677557, 0.24975673, 0.96702641],
       [0.90040327, 0.61196352, 0.85995196],
       [0.20660382, 0.84639322, 0.45869684],
       [0.43180773, 0.77621717, 0.17960785],
       [0.57433589, 0.02781011, 0.80034891]])

In [63]:
a2[0][0] = 100

In [64]:
a2

array([[1.00000000e+02, 1.78055495e-01, 5.71964169e-01],
       [3.47649241e-01, 4.06471429e-01, 2.91996254e-01],
       [4.06775565e-01, 2.49756728e-01, 9.67026410e-01],
       [9.00403275e-01, 6.11963520e-01, 8.59951958e-01],
       [2.06603815e-01, 8.46393216e-01, 4.58696837e-01],
       [4.31807731e-01, 7.76217172e-01, 1.79607852e-01],
       [5.74335891e-01, 2.78101074e-02, 8.00348914e-01]])

In [65]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [66]:
a

array([[1, 2],
       [3, 4]])

In [67]:
b

array([[2, 3],
       [4, 5]])

In [68]:
a*b

array([[ 2,  6],
       [12, 20]])

In [69]:
a.dot(b)

array([[10, 13],
       [22, 29]])

In [70]:
m = a@b

In [71]:
m

array([[10, 13],
       [22, 29]])

In [72]:
m/0

C:\Users\fazlu\AppData\Local\Temp/ipykernel_9624/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [73]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
6+np.zeros((4,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [75]:
np.empty((4,6))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        2.12199579e-314, 0.00000000e+000, 4.24399158e-314],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        4.24399158e-314, 0.00000000e+000, 8.48798317e-314],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        6.36598737e-314, 0.00000000e+000, 1.27319747e-313]])

In [76]:
np.empty((4,6,3))

array([[[ 0.00000000e+000,  1.58101007e-322,  6.95174602e-310],
        [ 4.94065646e-323,  5.43472210e-323, -7.21124778e+303],
        [             nan, -7.88629834e+303, -8.57075563e+303],
        [-3.91549710e+228,  1.39711812e-311,  6.95174621e-310],
        [-3.75667295e-184,  1.39711812e-311,  1.39711788e-311],
        [ 1.21229563e+003,  1.39711812e-311,  1.39711812e-311]],

       [[ 2.89396786e-179,  1.39710326e-311,  6.95174621e-310],
        [-4.02798650e+030,  1.39708094e-311,  6.95174619e-310],
        [ 2.38247789e-293,  1.39711812e-311,  6.95174621e-310],
        [-2.15551881e+129,  1.39711812e-311,  1.39707968e-311],
        [ 1.18685259e-104,  1.39711812e-311,  1.39707968e-311],
        [-5.83475710e+059,  1.39708536e-311,  1.39707991e-311]],

       [[ 2.10785827e+285,  1.39708508e-311,  6.95174620e-310],
        [ 2.80479184e+176,  1.39710353e-311,  6.95174619e-310],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.000000

In [77]:
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [78]:
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [79]:
np.linspace(2,5,10).reshape(5,2)

array([[2.        , 2.33333333],
       [2.66666667, 3.        ],
       [3.33333333, 3.66666667],
       [4.        , 4.33333333],
       [4.66666667, 5.        ]])

In [80]:
np.linspace(2,5,10,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
        3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ]),
 0.3333333333333333)

In [81]:
np.logspace(5,9,base=2)

array([ 32.        ,  33.86287719,  35.8342016 ,  37.9202865 ,
        40.12781264,  42.46384973,  44.93587901,  47.55181725,
        50.32004211,  53.24941894,  56.34932918,  59.62970042,
        63.10103819,  66.77445958,  70.66172888,  74.77529521,
        79.12833244,  83.73478136,  88.60939429,  93.76778239,
        99.2264656 , 105.00292557, 111.11566165, 117.58425012,
       124.4294069 , 131.67305388, 139.33838914, 147.44996121,
       156.03374774, 165.11723864, 174.72952417, 184.90138806,
       195.66540611, 207.05605052, 219.10980029, 231.86525805,
       245.36327366, 259.64707506, 274.76240671, 290.75767606,
       307.6841086 , 325.59591193, 344.55044931, 364.60842343,
       385.83407074, 408.29536724, 432.06424614, 457.21682824,
       483.83366569, 512.        ])

In [82]:
ab1=np.arange(10)

In [83]:
ab1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
ab1.max()

9

In [85]:
ab2=np.arange(4,40).reshape(2,6,3)

In [86]:
ab2

array([[[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]],

       [[22, 23, 24],
        [25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]]])

In [87]:
ab2.max(axis=1)

array([[19, 20, 21],
       [37, 38, 39]])

In [88]:
ab2[0][1][0]

7

In [89]:
pow(ab1,6)

array([     0,      1,     64,    729,   4096,  15625,  46656, 117649,
       262144, 531441], dtype=int32)

In [90]:
a = np.arange(4,50)

In [91]:
np.log10(a)

array([0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
       0.95424251, 1.        , 1.04139269, 1.07918125, 1.11394335,
       1.14612804, 1.17609126, 1.20411998, 1.23044892, 1.25527251,
       1.2787536 , 1.30103   , 1.32221929, 1.34242268, 1.36172784,
       1.38021124, 1.39794001, 1.41497335, 1.43136376, 1.44715803,
       1.462398  , 1.47712125, 1.49136169, 1.50514998, 1.51851394,
       1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
       1.59106461, 1.60205999, 1.61278386, 1.62324929, 1.63346846,
       1.64345268, 1.65321251, 1.66275783, 1.67209786, 1.68124124,
       1.69019608])

In [92]:
x = np.array([1,2,3])

In [93]:
y = x

In [94]:
y

array([1, 2, 3])

In [95]:
z = np.copy(x)

In [96]:
z

array([1, 2, 3])

In [97]:
x[0] = 100

In [98]:
y

array([100,   2,   3])

In [99]:
z

array([1, 2, 3])

In [100]:
id(x)

2827837059504

In [101]:
id(y)

2827837059504

In [102]:
id(z)

2827836973200

In [103]:
id(x[0])

2827836942000

In [104]:
id(y[0])

2827836941200

In [105]:
id(x[1])

2827836942320

In [106]:
id(y[1])

2827836942512

In [107]:
x = np.array([1,2,3])

In [108]:
y = x

In [109]:
id(x)

2827837124752

In [110]:
id(y)

2827837124752

In [111]:
id(x[0])

2827836942832

In [112]:
id(y[0])

2827836942704

In [113]:
su = np.array([457,345])

In [114]:
df = su

In [115]:
id(su)

2827837125616

In [116]:
id(df)

2827837125616

In [117]:
id(su[0])

2827836943120

In [118]:
id(df[0])

2827836943248

In [119]:
id(su[1]) == id(df[1])

True

In [120]:
id(su[1]) == id(df[0])

True

In [121]:
id(df) == id(su)

True

In [122]:
xt = np.array([34,67,89])

In [123]:
id(xt[0]) == id(su[0])

True

In [124]:
c = "sudh"

In [125]:
id(c) == id(su)

False

In [126]:
id(c[0]) == id(su[0])

False