In [1]:
import numpy as np

In [2]:
l = ["sudh", 1,2,3,4]

In [3]:
type(l)

list

In [4]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [5]:
type(np.array(l))

numpy.ndarray

In [12]:
a1 = np.array([3,2,4,5,6,3.0])

In [13]:
a = np.array([[1,2],[3,4]])

In [14]:
a

array([[1, 2],
       [3, 4]])

In [15]:
a[1][1]

4

In [17]:
a1

array([3., 2., 4., 5., 6., 3.])

In [18]:
a1[2]

4.0

In [26]:
a2 = np.array([1,2,3,4],ndmin=4)

In [27]:
a2

array([[[[1, 2, 3, 4]]]])

In [31]:
a2[0][0][0][0]

1

In [32]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [33]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [35]:
np.mat([1,2,3,4,5]) # minimun 2 dimension

matrix([[1, 2, 3, 4, 5]])

In [36]:
a = [1,2,3,4,5]

In [37]:
np.asarray(a)

array([1, 2, 3, 4, 5])

In [38]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [39]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [40]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [41]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [43]:
np.fromfunction(lambda i, j : i*j, (4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [44]:
np.mat(np.fromfunction(lambda i, j : i*j, (4,4), dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [48]:
np.fromfunction(lambda i, j,z : i*j*z, (4,3,2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [49]:
np.fromfunction(lambda i, j,z,p : i*j*z*p, (4,3,2,2), dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])