In [1]:
import numpy as np
import pandas as pd

In [2]:
l = ["sudh", 1,2,3,4]

In [3]:
type(l)

list

In [4]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [5]:
type(np.array(l))

numpy.ndarray

In [12]:
a1 = np.array([3,2,4,5,6,3.0])

In [13]:
a = np.array([[1,2],[3,4]])

In [14]:
a

array([[1, 2],
       [3, 4]])

In [15]:
a[1][1]

4

In [17]:
a1

array([3., 2., 4., 5., 6., 3.])

In [18]:
a1[2]

4.0

In [26]:
a2 = np.array([1,2,3,4],ndmin=4)

In [27]:
a2

array([[[[1, 2, 3, 4]]]])

In [31]:
a2[0][0][0][0]

1

In [32]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [33]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [35]:
np.mat([1,2,3,4,5]) # minimun 2 dimension

matrix([[1, 2, 3, 4, 5]])

In [36]:
a = [1,2,3,4,5]

In [37]:
np.asarray(a)

array([1, 2, 3, 4, 5])

In [38]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [39]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [40]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [41]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [43]:
np.fromfunction(lambda i, j : i*j, (4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [44]:
np.mat(np.fromfunction(lambda i, j : i*j, (4,4), dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [48]:
np.fromfunction(lambda i, j,z : i*j*z, (4,3,2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [50]:
a = np.fromfunction(lambda i, j,z,p : i*j*z*p, (4,3,2,2), dtype=int)

In [ ]:
Job Location- Work From Home
Interested candidates can share their resumes at Whatsapp Divya Ma'am: +918928482266

For more details Please Contact on +918928482266

In [51]:
a

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [56]:
a = np.fromfunction(lambda i, j,z: i*j*z, (4,3,2), dtype=int)

In [57]:
a.shape

(4, 3, 2)

In [58]:
a.ndim

3

In [59]:
a.size

24

In [60]:
a.dtype

dtype('int32')

In [61]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [64]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [69]:
a = np.fromfunction(lambda i, j: i*j, (100,100), dtype=int)

In [70]:
pd.DataFrame(a)

0   1    2    3    4    5    6    7    8    9   ...    90    91    92  \
0    0   0    0    0    0    0    0    0    0    0  ...     0     0     0   
1    0   1    2    3    4    5    6    7    8    9  ...    90    91    92   
2    0   2    4    6    8   10   12   14   16   18  ...   180   182   184   
3    0   3    6    9   12   15   18   21   24   27  ...   270   273   276   
4    0   4    8   12   16   20   24   28   32   36  ...   360   364   368   
..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
95   0  95  190  285  380  475  570  665  760  855  ...  8550  8645  8740   
96   0  96  192  288  384  480  576  672  768  864  ...  8640  8736  8832   
97   0  97  194  291  388  485  582  679  776  873  ...  8730  8827  8924   
98   0  98  196  294  392  490  588  686  784  882  ...  8820  8918  9016   
99   0  99  198  297  396  495  594  693  792  891  ...  8910  9009  9108   

      93    94    95    96    97    98    99  
0      0     0     0     0     0     0     0  
1     93    94    95    96    97    98    99  
2    186   188   190   192   194   196   198  
3    279   282   285   288   291   294   297  
4    372   376   380   384   388   392   396  
..   ...   ...   ...   ...   ...   ...   ...  
95  8835  8930  9025  9120  9215  9310  9405  
96  8928  9024  9120  9216  9312  9408  9504  
97  9021  9118  9215  9312  9409  9506  9603  
98  9114  9212  9310  9408  9506  9604  9702  
99  9207  9306  9405  9504  9603  9702  9801  

[100 rows x 100 columns]

In [72]:
np.random.rand(100,4)

array([[6.66851676e-01, 7.26804393e-01, 8.00275517e-01, 5.97491050e-01],
       [7.15607521e-01, 7.26393259e-01, 2.44910369e-01, 5.17565515e-01],
       [4.23389565e-01, 6.45306549e-01, 9.97669942e-01, 4.24225292e-01],
       [1.41037570e-01, 9.83384443e-01, 4.87906617e-01, 5.97622053e-01],
       [7.65521739e-01, 7.69217542e-01, 5.13151628e-01, 9.87713052e-01],
       [4.74642160e-01, 9.83336890e-01, 3.17010454e-01, 8.11598993e-01],
       [8.28704101e-01, 9.99369494e-01, 8.38301362e-01, 9.72794500e-01],
       [6.27202751e-01, 8.24167913e-03, 1.93833975e-01, 2.86334769e-01],
       [6.76535157e-01, 6.71478062e-01, 9.00856921e-01, 3.27640549e-01],
       [9.70402985e-01, 4.45979359e-02, 7.15447845e-01, 3.95034480e-01],
       [6.06726990e-01, 4.45564493e-01, 8.03882159e-01, 5.02592378e-01],
       [4.26746986e-01, 3.02258419e-01, 6.69346456e-01, 9.45718760e-01],
       [8.17772102e-01, 2.93160427e-02, 6.72699153e-01, 2.35834183e-02],
       [8.26794232e-01, 7.01552353e-01, 2.83151759e

In [73]:
np.random.randint(4,50)

31

In [75]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  0.112427 -0.114261 -1.484040 -0.498075 -1.477931
1 -0.937763 -1.156337 -0.428225 -0.580314 -0.215414
2 -0.015074  0.057178  1.048526  0.049542  0.437978
3  2.329876  1.850612 -0.873721  0.498196 -0.069431

In [80]:
a = np.fromfunction(lambda i, j,z: i*j*z, (4,3,2), dtype=int)
a.size

24

In [85]:
a.reshape(4,2,1,3,1,1)

array([[[[[[0]],

          [[0]],

          [[0]]]],



        [[[[0]],

          [[0]],

          [[0]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[1]],

          [[0]],

          [[2]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[2]],

          [[0]],

          [[4]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[3]],

          [[0]],

          [[6]]]]]])

In [86]:
a.reshape(4,3,2)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [88]:
 a.reshape(4,-1) # here -1 is the remaing fraction of a took by function

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [89]:
a.reshape(2,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [91]:
a.reshape(2,-12345) # any negative number will work 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [92]:
a.reshape(2,4,-125)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [84]:
pd.DataFrame(a.reshape(6,4)) # must be the fraction of size of a

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [101]:
list(range(4,10,2))

[4, 6, 8]

In [102]:
a1 = list(np.arange(4,10.5,0.2))

In [103]:
a1

[4.0,
 4.2,
 4.4,
 4.6000000000000005,
 4.800000000000001,
 5.000000000000001,
 5.200000000000001,
 5.400000000000001,
 5.600000000000001,
 5.800000000000002,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.800000000000003,
 8.000000000000004,
 8.200000000000003,
 8.400000000000004,
 8.600000000000005,
 8.800000000000004,
 9.000000000000004,
 9.200000000000005,
 9.400000000000006,
 9.600000000000005,
 9.800000000000004,
 10.000000000000005,
 10.200000000000006,
 10.400000000000006]

In [104]:
a1[1:4]

[4.2, 4.4, 4.6000000000000005]

In [105]:
arr = np.random.rand(4,5)

In [106]:
arr

array([[0.75866156, 0.60418699, 0.73018385, 0.18843478, 0.03746727],
       [0.98408563, 0.97302855, 0.11441976, 0.37871172, 0.29475348],
       [0.51079858, 0.55411951, 0.67228125, 0.10115438, 0.06293163],
       [0.64408278, 0.47310498, 0.1049733 , 0.79937124, 0.14047278]])

In [108]:
arr[arr > 0.5]

array([0.75866156, 0.60418699, 0.73018385, 0.98408563, 0.97302855,
       0.51079858, 0.55411951, 0.67228125, 0.64408278, 0.79937124])

In [115]:
arr[1:3,2:3]

array([[0.11441976],
       [0.67228125]])

In [128]:
arr[[1,2],[2]]

array([0.78479882, 0.725269  ])

In [129]:
arr = np.random.rand(8,5)

In [130]:
arr

array([[0.76042499, 0.31738608, 0.21762647, 0.3221186 , 0.44414349],
       [0.58885412, 0.46536751, 0.47747516, 0.3370404 , 0.89351997],
       [0.50421375, 0.27616468, 0.50747238, 0.04037547, 0.35640081],
       [0.04565997, 0.95898395, 0.30805543, 0.9803797 , 0.83614072],
       [0.47275332, 0.11863729, 0.25828289, 0.97599405, 0.24461933],
       [0.65854507, 0.76144239, 0.80725499, 0.24081992, 0.00781317],
       [0.23291222, 0.69336677, 0.9161087 , 0.92181432, 0.80160698],
       [0.92852854, 0.4451359 , 0.42773701, 0.1916805 , 0.00525627]])

In [131]:
arr[1:8,0:2]

array([[0.58885412, 0.46536751],
       [0.50421375, 0.27616468],
       [0.04565997, 0.95898395],
       [0.47275332, 0.11863729],
       [0.65854507, 0.76144239],
       [0.23291222, 0.69336677],
       [0.92852854, 0.4451359 ]])

In [133]:
a2 = arr[1:8,[0,1,2]]

In [134]:
a2

array([[0.58885412, 0.46536751, 0.47747516],
       [0.50421375, 0.27616468, 0.50747238],
       [0.04565997, 0.95898395, 0.30805543],
       [0.47275332, 0.11863729, 0.25828289],
       [0.65854507, 0.76144239, 0.80725499],
       [0.23291222, 0.69336677, 0.9161087 ],
       [0.92852854, 0.4451359 , 0.42773701]])

In [135]:
a2[0][0] = 100

In [136]:
a2

array([[1.00000000e+02, 4.65367515e-01, 4.77475158e-01],
       [5.04213748e-01, 2.76164680e-01, 5.07472381e-01],
       [4.56599739e-02, 9.58983950e-01, 3.08055426e-01],
       [4.72753316e-01, 1.18637288e-01, 2.58282892e-01],
       [6.58545073e-01, 7.61442387e-01, 8.07254988e-01],
       [2.32912218e-01, 6.93366772e-01, 9.16108700e-01],
       [9.28528539e-01, 4.45135899e-01, 4.27737012e-01]])

In [140]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [141]:
a

array([[1, 2],
       [3, 4]])

In [142]:
b

array([[2, 3],
       [4, 5]])

In [143]:
a*b

array([[ 2,  6],
       [12, 20]])

In [144]:
a.dot(b)

array([[10, 13],
       [22, 29]])

In [147]:
m = a@b

In [148]:
m

array([[10, 13],
       [22, 29]])

In [149]:
m/0

C:\Users\fazlu\AppData\Local\Temp/ipykernel_1648/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [8]:
a = np.arange(4,50)

In [9]:
np.log10(a)

array([0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
       0.95424251, 1.        , 1.04139269, 1.07918125, 1.11394335,
       1.14612804, 1.17609126, 1.20411998, 1.23044892, 1.25527251,
       1.2787536 , 1.30103   , 1.32221929, 1.34242268, 1.36172784,
       1.38021124, 1.39794001, 1.41497335, 1.43136376, 1.44715803,
       1.462398  , 1.47712125, 1.49136169, 1.50514998, 1.51851394,
       1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
       1.59106461, 1.60205999, 1.61278386, 1.62324929, 1.63346846,
       1.64345268, 1.65321251, 1.66275783, 1.67209786, 1.68124124,
       1.69019608])

In [10]:
x = np.array([1,2,3])

In [11]:
y = x

In [12]:
y

array([1, 2, 3])

In [13]:
z = np.copy(x)

In [14]:
z

array([1, 2, 3])

In [15]:
x[0] = 100

In [16]:
y

array([100,   2,   3])

In [17]:
z

array([1, 2, 3])

In [18]:
id(x)

2447537501840

In [19]:
id(y)

2447537501840

In [20]:
id(z)

2447537503760

In [21]:
id(x[0])

2447536747216

In [22]:
id(y[0])

2447536747216

In [23]:
id(x[1])

2447536747952

In [24]:
id(y[1])

2447536747952

In [25]:
x = np.array([1,2,3])

In [26]:
y = x

In [27]:
id(x)

2447537502416

In [28]:
id(y)

2447537502416

In [29]:
id(x[0])

2447536748880

In [30]:
id(y[0])

2447536748528

In [32]:
su = np.array([457,345])

In [33]:
df = su

In [34]:
id(su)

2447537750448

In [35]:
id(df)

2447537750448

In [36]:
id(su[0])

2447536749168

In [37]:
id(df[0])

2447536748912

In [39]:
id(su[1]) == id(df[1])

True

In [40]:
id(su[1]) == id(df[0])

True

In [41]:
id(df) == id(su)

True

In [42]:
xt = np.array([34,67,89])

In [43]:
id(xt[0]) == id(su[0])

True