In [29]:
import numpy as np
import pandas as pd

In [30]:
l = ["sudh", 1,2,3,4]

In [31]:
type(l)

list

In [32]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [33]:
type(np.array(l))

numpy.ndarray

In [34]:
a1 = np.array([3,2,4,5,6,3.0])

In [35]:
a = np.array([[1,2],[3,4]])

In [36]:
a

array([[1, 2],
       [3, 4]])

In [37]:
a[1][1]

4

In [38]:
a1

array([3., 2., 4., 5., 6., 3.])

In [39]:
a1[2]

4.0

In [40]:
a2 = np.array([1,2,3,4],ndmin=4)

In [41]:
a2

array([[[[1, 2, 3, 4]]]])

In [42]:
a2[0][0][0][0]

1

In [43]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [44]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [45]:
np.mat([1,2,3,4,5]) # minimun 2 dimension

matrix([[1, 2, 3, 4, 5]])

In [46]:
a = [1,2,3,4,5]

In [47]:
np.asarray(a)

array([1, 2, 3, 4, 5])

In [48]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [49]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [50]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [51]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [52]:
np.fromfunction(lambda i, j : i*j, (4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [53]:
np.mat(np.fromfunction(lambda i, j : i*j, (4,4), dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [54]:
np.fromfunction(lambda i, j,z : i*j*z, (4,3,2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [55]:
a = np.fromfunction(lambda i, j,z,p : i*j*z*p, (4,3,2,2), dtype=int)

In [56]:
Job Location- Work From Home
Interested candidates can share their resumes at Whatsapp Divya Ma'am: +918928482266

For more details Please Contact on +918928482266

SyntaxError: invalid syntax (Temp/ipykernel_6048/1995618633.py, line 1)

In [57]:
a

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [58]:
a = np.fromfunction(lambda i, j,z: i*j*z, (4,3,2), dtype=int)

In [59]:
a.shape

(4, 3, 2)

In [60]:
a.ndim

3

In [61]:
a.size

24

In [62]:
a.dtype

dtype('int32')

In [63]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [64]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [65]:
a = np.fromfunction(lambda i, j: i*j, (100,100), dtype=int)

In [66]:
pd.DataFrame(a)

0   1    2    3    4    5    6    7    8    9   ...    90    91    92  \
0    0   0    0    0    0    0    0    0    0    0  ...     0     0     0   
1    0   1    2    3    4    5    6    7    8    9  ...    90    91    92   
2    0   2    4    6    8   10   12   14   16   18  ...   180   182   184   
3    0   3    6    9   12   15   18   21   24   27  ...   270   273   276   
4    0   4    8   12   16   20   24   28   32   36  ...   360   364   368   
..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
95   0  95  190  285  380  475  570  665  760  855  ...  8550  8645  8740   
96   0  96  192  288  384  480  576  672  768  864  ...  8640  8736  8832   
97   0  97  194  291  388  485  582  679  776  873  ...  8730  8827  8924   
98   0  98  196  294  392  490  588  686  784  882  ...  8820  8918  9016   
99   0  99  198  297  396  495  594  693  792  891  ...  8910  9009  9108   

      93    94    95    96    97    98    99  
0      0     0     0     0     0     0     0  
1     93    94    95    96    97    98    99  
2    186   188   190   192   194   196   198  
3    279   282   285   288   291   294   297  
4    372   376   380   384   388   392   396  
..   ...   ...   ...   ...   ...   ...   ...  
95  8835  8930  9025  9120  9215  9310  9405  
96  8928  9024  9120  9216  9312  9408  9504  
97  9021  9118  9215  9312  9409  9506  9603  
98  9114  9212  9310  9408  9506  9604  9702  
99  9207  9306  9405  9504  9603  9702  9801  

[100 rows x 100 columns]

In [67]:
np.random.rand(100,4)

array([[3.79700578e-02, 5.75990561e-01, 8.19884386e-01, 6.83387938e-02],
       [3.21587533e-01, 7.00835297e-01, 7.00592696e-01, 7.11560856e-01],
       [9.25162939e-01, 5.84188130e-01, 2.88415428e-01, 9.58054592e-01],
       [2.73415129e-01, 8.83058747e-01, 1.66562198e-01, 1.80871007e-01],
       [7.75980551e-01, 9.75767670e-01, 7.10351161e-01, 3.16949188e-01],
       [4.92766097e-01, 7.61682577e-01, 8.35869196e-01, 1.42149080e-01],
       [5.96686155e-02, 3.58421063e-01, 9.74179069e-01, 7.96226130e-01],
       [1.72550163e-01, 1.82046340e-01, 3.88909042e-01, 7.46839928e-01],
       [5.45238343e-01, 1.75090143e-01, 1.42028773e-01, 6.14712326e-01],
       [6.73898643e-02, 5.47909639e-01, 7.47554565e-01, 5.63263452e-01],
       [9.61115322e-02, 5.98402047e-01, 8.92503084e-01, 2.56737809e-01],
       [1.98622790e-01, 3.35137473e-01, 7.16297417e-01, 8.23805777e-01],
       [5.84731085e-01, 9.95665971e-01, 2.99270384e-02, 9.43937127e-01],
       [3.22086463e-01, 2.76572628e-01, 7.16068965e

In [68]:
np.random.randint(4,50)

5

In [69]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  0.481749  0.803446  0.329952  0.596469  0.925773
1 -0.559242 -0.701621  2.304683 -0.233059  0.956393
2  0.430843  0.730873 -0.163522 -1.545523 -1.231656
3 -1.407090  0.290948 -0.183889 -0.476569  0.397441

In [70]:
a = np.fromfunction(lambda i, j,z: i*j*z, (4,3,2), dtype=int)
a.size

24

In [71]:
a.reshape(4,2,1,3,1,1)

array([[[[[[0]],

          [[0]],

          [[0]]]],



        [[[[0]],

          [[0]],

          [[0]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[1]],

          [[0]],

          [[2]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[2]],

          [[0]],

          [[4]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[3]],

          [[0]],

          [[6]]]]]])

In [72]:
a.reshape(4,3,2)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [73]:
 a.reshape(4,-1) # here -1 is the remaing fraction of a took by function

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [74]:
a.reshape(2,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [75]:
a.reshape(2,-12345) # any negative number will work 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [76]:
a.reshape(2,4,-125)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [77]:
pd.DataFrame(a.reshape(6,4)) # must be the fraction of size of a

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [78]:
list(range(4,10,2))

[4, 6, 8]

In [79]:
a1 = list(np.arange(4,10.5,0.2))

In [80]:
a1

[4.0,
 4.2,
 4.4,
 4.6000000000000005,
 4.800000000000001,
 5.000000000000001,
 5.200000000000001,
 5.400000000000001,
 5.600000000000001,
 5.800000000000002,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.800000000000003,
 8.000000000000004,
 8.200000000000003,
 8.400000000000004,
 8.600000000000005,
 8.800000000000004,
 9.000000000000004,
 9.200000000000005,
 9.400000000000006,
 9.600000000000005,
 9.800000000000004,
 10.000000000000005,
 10.200000000000006,
 10.400000000000006]

In [81]:
a1[1:4]

[4.2, 4.4, 4.6000000000000005]

In [82]:
arr = np.random.rand(4,5)

In [83]:
arr

array([[0.72678206, 0.75676059, 0.39831653, 0.06431879, 0.40478526],
       [0.01589161, 0.57059165, 0.35293478, 0.85344061, 0.06327443],
       [0.40377414, 0.28402801, 0.36248113, 0.95982883, 0.38646652],
       [0.69529514, 0.84677662, 0.94782171, 0.57217076, 0.03865592]])

In [84]:
arr[arr > 0.5]

array([0.72678206, 0.75676059, 0.57059165, 0.85344061, 0.95982883,
       0.69529514, 0.84677662, 0.94782171, 0.57217076])

In [85]:
arr[1:3,2:3]

array([[0.35293478],
       [0.36248113]])

In [86]:
arr[[1,2],[2]]

array([0.35293478, 0.36248113])

In [87]:
arr = np.random.rand(8,5)

In [88]:
arr

array([[0.5207454 , 0.41086618, 0.73808737, 0.08205535, 0.84386942],
       [0.43065041, 0.97246916, 0.15569023, 0.51330247, 0.32931245],
       [0.28921206, 0.0732684 , 0.93559348, 0.83022772, 0.28182398],
       [0.82435303, 0.04730521, 0.30686776, 0.33548258, 0.97385701],
       [0.32299902, 0.84950867, 0.71205468, 0.88997352, 0.5700074 ],
       [0.15355843, 0.33306753, 0.42415218, 0.66982559, 0.89552432],
       [0.98239999, 0.52938729, 0.29642148, 0.71858409, 0.25245172],
       [0.23760185, 0.62254615, 0.97814858, 0.39916696, 0.97349798]])

In [89]:
arr[1:8,0:2]

array([[0.43065041, 0.97246916],
       [0.28921206, 0.0732684 ],
       [0.82435303, 0.04730521],
       [0.32299902, 0.84950867],
       [0.15355843, 0.33306753],
       [0.98239999, 0.52938729],
       [0.23760185, 0.62254615]])

In [90]:
a2 = arr[1:8,[0,1,2]]

In [91]:
a2

array([[0.43065041, 0.97246916, 0.15569023],
       [0.28921206, 0.0732684 , 0.93559348],
       [0.82435303, 0.04730521, 0.30686776],
       [0.32299902, 0.84950867, 0.71205468],
       [0.15355843, 0.33306753, 0.42415218],
       [0.98239999, 0.52938729, 0.29642148],
       [0.23760185, 0.62254615, 0.97814858]])

In [92]:
a2[0][0] = 100

In [93]:
a2

array([[1.00000000e+02, 9.72469160e-01, 1.55690227e-01],
       [2.89212063e-01, 7.32683999e-02, 9.35593479e-01],
       [8.24353029e-01, 4.73052081e-02, 3.06867758e-01],
       [3.22999015e-01, 8.49508669e-01, 7.12054677e-01],
       [1.53558434e-01, 3.33067533e-01, 4.24152181e-01],
       [9.82399992e-01, 5.29387294e-01, 2.96421482e-01],
       [2.37601848e-01, 6.22546151e-01, 9.78148578e-01]])

In [94]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [95]:
a

array([[1, 2],
       [3, 4]])

In [96]:
b

array([[2, 3],
       [4, 5]])

In [97]:
a*b

array([[ 2,  6],
       [12, 20]])

In [98]:
a.dot(b)

array([[10, 13],
       [22, 29]])

In [99]:
m = a@b

In [100]:
m

array([[10, 13],
       [22, 29]])

In [101]:
m/0

C:\Users\fazlu\AppData\Local\Temp/ipykernel_6048/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [102]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [103]:
6+np.zeros((4,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [104]:
np.empty((4,6))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        2.12199579e-314, 0.00000000e+000, 4.24399158e-314],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        4.24399158e-314, 0.00000000e+000, 8.48798317e-314],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        6.36598737e-314, 0.00000000e+000, 1.27319747e-313]])

In [105]:
np.empty((4,6,3))

array([[[ 0.00000000e+000,  1.58101007e-322,  6.95177187e-310],
        [ 4.94065646e-323,  5.43472210e-323, -7.54342059e+303],
        [ 3.03403406e-294,  1.32195286e-279,              nan],
        [ 3.61579821e-152,  1.11200640e-311,  6.95177206e-310],
        [-6.04216138e-091,  1.11200640e-311,  1.11200617e-311],
        [ 2.40303143e+085,  1.11200640e-311,  1.11200640e-311]],

       [[ 3.59469906e-154,  1.11199151e-311,  6.95177206e-310],
        [-1.03794176e+131,  1.11196664e-311,  6.95177205e-310],
        [-4.53383829e+011,  1.11200640e-311,  6.95177206e-310],
        [ 1.15417514e+308,  1.11200640e-311,  1.11196602e-311],
        [-1.34458927e+282,  1.11200641e-311,  1.11196602e-311],
        [-6.89920723e+307,  1.11197361e-311,  1.11196626e-311]],

       [[-3.28775371e+011,  1.11197333e-311,  6.95177205e-310],
        [-1.27768808e+241,  1.11199179e-311,  6.95177205e-310],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.000000

In [106]:
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [107]:
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [108]:
np.linspace(2,5,10).reshape(5,2)

array([[2.        , 2.33333333],
       [2.66666667, 3.        ],
       [3.33333333, 3.66666667],
       [4.        , 4.33333333],
       [4.66666667, 5.        ]])

In [109]:
np.linspace(2,5,10,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
        3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ]),
 0.3333333333333333)

In [110]:
np.logspace(5,9,base=2)

array([ 32.        ,  33.86287719,  35.8342016 ,  37.9202865 ,
        40.12781264,  42.46384973,  44.93587901,  47.55181725,
        50.32004211,  53.24941894,  56.34932918,  59.62970042,
        63.10103819,  66.77445958,  70.66172888,  74.77529521,
        79.12833244,  83.73478136,  88.60939429,  93.76778239,
        99.2264656 , 105.00292557, 111.11566165, 117.58425012,
       124.4294069 , 131.67305388, 139.33838914, 147.44996121,
       156.03374774, 165.11723864, 174.72952417, 184.90138806,
       195.66540611, 207.05605052, 219.10980029, 231.86525805,
       245.36327366, 259.64707506, 274.76240671, 290.75767606,
       307.6841086 , 325.59591193, 344.55044931, 364.60842343,
       385.83407074, 408.29536724, 432.06424614, 457.21682824,
       483.83366569, 512.        ])

In [111]:
ab1=np.arange(10)

In [112]:
ab1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [113]:
ab1.max()

9

In [114]:
ab2=np.arange(4,40).reshape(2,6,3)

In [115]:
ab2

array([[[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]],

       [[22, 23, 24],
        [25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]]])

In [116]:
ab2.max(axis=1)

array([[19, 20, 21],
       [37, 38, 39]])

In [117]:
ab2[0][1][0]

7

In [118]:
pow(ab1,6)

array([     0,      1,     64,    729,   4096,  15625,  46656, 117649,
       262144, 531441], dtype=int32)

In [ ]:
a = np.arange(4,50)

In [ ]:
np.log10(a)

In [ ]:
x = np.array([1,2,3])

In [ ]:
y = x

In [ ]:
y

In [ ]:
z = np.copy(x)

In [ ]:
z

In [ ]:
x[0] = 100

In [ ]:
y

In [ ]:
z

In [ ]:
id(x)

In [ ]:
id(y)

In [ ]:
id(z)

In [ ]:
id(x[0])

In [ ]:
id(y[0])

In [ ]:
id(x[1])

In [ ]:
id(y[1])

In [ ]:
x = np.array([1,2,3])

In [ ]:
y = x

In [ ]:
id(x)

In [ ]:
id(y)

In [ ]:
id(x[0])

In [ ]:
id(y[0])

In [ ]:
su = np.array([457,345])

In [ ]:
df = su

In [ ]:
id(su)

In [ ]:
id(df)

In [ ]:
id(su[0])

In [ ]:
id(df[0])

In [ ]:
id(su[1]) == id(df[1])

In [ ]:
id(su[1]) == id(df[0])

In [ ]:
id(df) == id(su)

In [ ]:
xt = np.array([34,67,89])

In [ ]:
id(xt[0]) == id(su[0])

In [ ]:
c = "sudh"

In [ ]:
id(c) == id(su)